pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('EasyEraFE/EazyEra') { // Change to the Angular project directory
                    script {
                        sh 'ls -al'
                        sh 'pwd'
                        sh 'npm install'
                        sh 'ng build'
                    }
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('EasyEraFE/EazyEra') { // Change to the Angular project directory
                    script {
                        sh 'ng test --watch=false --code-coverage'
                    }
                }
            }
        }

        stage('E2E Tests') {
            steps {
                dir('EasyEraFE/EazyEra') { // Change to the Angular project directory
                    script {
                        sh 'ng e2e'
                    }
                }
            }
        }

        // Add more stages if needed, e.g., for deployment
    }

    post {
        always {
            // Example action: clean up workspace
            cleanWs()
            // Or simply echo a message
            echo 'Pipeline execution is complete.'
        }
    }
}
